site_name: teamly.py

nav:
  - Home: index.md
  - About:
      - License: about/license.md
      - Release Notes: about/release-notes.md

repo_name: GitHub
repo_url: https://github.com/MrFatihLD/teamly.py
edit_uri: ""

copyright: MrFatihLD

theme:
  name: mkdocs
  locale: en
  color_mode: auto
  user_color_mode_toggle: true

markdown_extensions:
  - admonition
  - attr_list
